# 指定 Docker Compose 文件版本
version: '3.8'

services:
  # 定义后端 API 服务
  api:
    build: 
      # 指定构建上下文为项目根目录
      context: ../..
      # 指定 Dockerfile 的位置
      dockerfile: deployment/docker/Dockerfile
    ports:
      # 将容器的 8000 端口映射到主机的 8000 端口
      - "8000:8000"
    environment:
      # 设置数据库连接 URL 环境变量
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/score_man
    depends_on:
      # 确保数据库服务先启动
      - db
    
  # 定义 MySQL 数据库服务
  db:
    # 使用 MySQL 5.7 版本的官方镜像
    image: mysql:5.7
    environment:
      # 设置 MySQL 环境变量
      - MYSQL_ROOT_PASSWORD=admin123  # root 用户密码
      - MYSQL_DATABASE=taskman        # 初始数据库名
      - MYSQL_USER=root              # 创建的用户名
      - MYSQL_PASSWORD=123           # 用户密码
    ports:
      # 将容器的 3306 端口映射到主机的 3306 端口
      - "3306:3306"
    volumes:
      # 将数据持久化到 named volume
      - mysql_data:/var/lib/mysql

# 定义持久化存储卷
volumes:
  mysql_data:  # MySQL 数据的持久化存储